Added dockerfile

diff --git a/scripts/redeploy b/scripts/redeploy
--- a/scripts/redeploy
+++ b/scripts/redeploy
@@ -62,13 +62,13 @@ while true; do
 		--)
 				shift; break;;
 		*) 
-				echo "Interanl error!"; exit 1;;
+				echo "Internal error!"; exit 1;;
 	esac
 done
 
 if [ "${catalina}" != "" -a "${tomcat}" != "" ]; then
 	echo "You cannot specify both catalina and tomcat options at the same time!"
-	exit -1
+	exit 1
 elif [ "${catalina}" == "" -a "${tomcat}" == "" ]; then
 	tomcat="tomcat7"
 fi
@@ -85,7 +85,7 @@ fi
 if [ ! -f endpoint/target/strabon-endpoint-*.war ]; then
 	echo "File endpoint/target/strabon-endpoint-*.war cannot be found."
 	echo "This script must be executed in Strabon folder"
-	exit -1
+	exit 1
 fi
 
 if [ "`ls ${webapps}|grep war|grep -v ${endpoint}.war`" != "" ];then
